#########################################################################################
server:
  port: 8080 # 服务端口号
#########################################################################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/apijson
    username: postgres
    password: 123456
  jackson:
    time-zone: GMT+8    # 设置时区为东八区
    date-format: yyyy-MM-dd HH:mm:ss # 设置时间格式
  output:
    ansi:
      enabled: DETECT
logging:
  file: apijson.log